### ISSUE TITLE
Set up CI for testing / publishing

### ISSUE THREAD

**Issue by stefsmeets** [DecodingRaphael/unraphael#14]
We can set up CI for:
1. [x] Testing the code
2. [x] Publishing to pypi -> follow-up: #27 
3. [x] Publishing to Zenodo -> follow-up: #26 
4. [x] Publishing to rtd (#12)
