### ISSUE TITLE
Set up dashboard GUI

### ISSUE THREAD

**Issue by stefsmeets** [DecodingRaphael/unraphael#16]
The GUI must be able to do the workflow:

- [x] Load set of images -> #18
- Calculate similarity based on some metric, eventually:
  - [x] SIFT -> #18 
  - [ ] Outline
  - [ ] Scale
  - [x] ORB -> #19 
- [x] Show heatmap/dendrogram -> #18
- [x] Make metrics configurable (expose options) -> #19 
- [x] Use carrousel for displaying images -> #21 
    - https://github.com/vivien000/st-clickable-images
    - https://github.com/jrieke/streamlit-image-select

**Comment by stefsmeets** [comment]
We have a dashboard-based gui now, so I think this issue can be closed. We can pick up any new pages / features in separate issues.
