### ISSUE TITLE
Fix bugs in normalization page

### ISSUE THREAD

**Issue by stefsmeets** [DecodingRaphael/unraphael#57]
## Width

- [x] Fix width defaulting to 0 -> #66 
- [x] Change width -> equalize width checkbox/number input instead -> #66 
- [x] Factor width out of load_images -> #66 
- [ ] Check if cropping in addition to setting equal width is preferred over resizing (as is currently done)

## Docs/layout

- [x] Add page to readme -> #65
- [x] Rename normalization -> compare -> #65 
- [x] Add progress bar(?) to homography -> #60
- [x] Display images in color -> #59 

## Additional features

- [x] Option to lay aligned contours on top of each other, in addition to use zoom streamlit component to zoom in on differences
- [x] Animation of two aligned images

## Metrics

#68 lays the groundwork for getting images back to the dashboard and displaying them. There is some work to select the right metrics and do better formatting.

- [x] From the homography or similar type of matrix, depending on which procedure is used, extract information on degree of rotation. This information will be put below the aligned image.
- [x] Return dict with equalization parameters on brightness, sharpness and contrast from equalization pre-processing step, and display these in the dashboard (at equalization parameters section?) -> #68
- [x] #98
- [x] Add units/formatting to metrics

## Bugs

- [x] fft phase correlation: fix format error when angle == None, in fft phase correlation
- [x] homography: fix unpacking error -> #60
- [x] Fix black screen -> #58 
- [x] Fourier mellon -> #64 
- [x] All alignment procedures crash, because image in other input form?
- [x] After selecting another aligned image to compare with, the alignment process starts again. However, all images are aligned in one go, so the alignment process should not start again -> solved by caching in #63

## Performance

- [x] Add caching to normalization page -> #63 
- [x] decouple equalization stop from alignment step in `align_all_selected_images_to_template` -> #59 
- [x] Add page to tests -> #61

**Comment by stefsmeets** [comment]
Hi @ThijsVroegh I think I addressed all the things I wanted in this issue, could you have a look at the other metrics to add? Or tell me what you had in mind, then I am also happy to implement it 😅

**Comment by ThijsVroegh** [comment]
Hi @stefsmeets, great! ;-)

Perhaps for clarity we should only provide the absolute values ​​for the template base image and the value after equalization of the aligned image? For example for sharpness: only the sharpness_template and sharpness_normalized (these values ​​are very close to each other, and give the user the information that the equalization was successful). What do you think?

Yes, I studied the appropriate metrics that we should include for the present purposes. I came up with this list of measures which, taken together, cover different but relevant aspects for similarity assessment. Of course, we can reduce its amount if needed:

•	Structural Similarity Metrics: SSIM, MS-SSIM, CW-SSIM, IW-SSIM
•	Perceptual Similarity Metrics: FSIM, VIF, LPIPS, PieAPP
•	Gradient-Based Metrics: GMSD, MDSI, DISTS
•	Saliency-Based Metrics: SR-SIM, VSI

All these measures can be calculated with PyTorch Image Quality (https://pypi.org/project/piq/) except for CW-SSIM which I found to be available in the pyssim package (https://pypi.org/project/pyssim/)
 
Each category of metrics is valauable when dealing with highly similar images where subtle differences might exist. My idea was that, by using a combination of these metrics, we can obtain a comprehensive evaluation that covers various aspects of structural, perceptual, and detailed similarities or differences between images. Finally, these metrics come in hand in the cluster process as well, so lets think about developing a widget that can be used in several pages

**Comment by ThijsVroegh** [comment]
@stefsmeets ;  I agree on ".... some of the metrics we calculate in the equalize functions, we may instead calculate them regardless of whether the step was carried out."  So when not carrying out the equalisation, the values for brightness ,contrast and sharpness are provided for both the base and aligned image along side the slider-output to inform the user about the magnitude of difference in these parameters
